server:
  port: 0
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_ANALYTICS}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc_time_zone: UTC
        default_schema: analytics
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/