server:
  port: 0
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_RACK}
    username: root
    password: ${MYSQL_PASSWORD}
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}