server:
  port: 8079
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:

        # M1: Precios de las reservas
        - id: M1-reservation-prices-service
          uri: lb://reservation-prices-service
          predicates:
            - Path=/tgs/rmkarts/reservationprice/**

        # M2: Descuento por tamaño de grupo
        - id: M2-quantity-discount-service
          uri: lb://quantity-discount-service
          predicates:
            - Path=/tgs/rmkarts/quantity/**

        # M3: Descuento por cliente frecuente
        - id: M3-frequency-discount-service
          uri: lb://frequency-discount-service
          predicates:
            - Path=/tgs/rmkarts/freq/**

        # M4: Tarifa de días especiales
        - id: M4-speial-day-service
          uri: lb://special-day-service
          predicates:
            - Path=/tgs/rmkarts/specialday/**

        # M5: Creación de vouchers
        - id: M5-voucher-service 
          uri: lb://voucher-service
          predicates:
            - Path=/tgs/rmkarts/voucher/**

        # M6: Rack
        - id: M6-reservation-service
          uri: lb://rack-service
          predicates:
            - Path=/tgs/rmkarts/reservation/**

        # M7: Resportes de Ingresos
        - id: M7-analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/tgs/rmkarts/analytics/**