server:
  port: 0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rmkarts
    username: root
    password: Juanpablo616
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/