server:
  port: 0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rack
    username: root
    password: Juanpablo616
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc_time_zone: UTC
        default_schema: rack
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/